---
- name: Docker status.
  hosts: all
  gather_facts: false
  become: true


  tasks:
    - name: Check the status of a docker container.
      ansible.builtin.command: docker ps -a
      register: my_output
      changed_when: my_output.rc != 0 # <- Uses the return code to define when the task has changed.

    - name: Show the status of a docker container.
      ansible.builtin.debug:
        var: my_output.stdout_lines
