---
- name: Upgrade all Packages.
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Perform Dist-Upgrade.
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true

    - name: Check If Reboot Is Required.
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Remove Dependencies That Are No Longer Required.
      ansible.builtin.apt:
        autoremove: true

    - name: Show Reboot Required Message.
      ansible.builtin.debug:
        msg: Reboot required.
      when: reboot_required_file.stat.exists
